# -*- coding: utf-8 -*-
"""Hierarchical Clustring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZakgRgLPi3uVDmH3KgTDavSD1pFCQVE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('/content/drive/MyDrive/ML Dataset/CLUSTERING.csv')
dataset

dataset.describe()

dataset.info()

#linkages -1)single 2)average 3)complate 4)centroid 5)ward
#limitations and advantages of all linkages

X=dataset.iloc[:,:].values

from sklearn.cluster import AgglomerativeClustering

import scipy.cluster.hierarchy as sch

dendrogram=sch.dendrogram(sch.linkage(X,method='ward'))

hc=AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='ward')

predict_hc=hc.fit_predict(X)
predict_hc

#visualization
plt.scatter(X[predict_hc==0,0],X[predict_hc==0,1],c='blue', label='Cluster0')
plt.scatter(X[predict_hc==1,0],X[predict_hc==1,1],c='green', label='Cluster1')
plt.scatter(X[predict_hc==2,0],X[predict_hc==2,1],c='red', label='Cluster2')
plt.scatter(X[predict_hc==3,0],X[predict_hc==3,1],c='yellow', label='Cluster3')
plt.scatter(X[predict_hc==4,0],X[predict_hc==4,1],c='black', label='Cluster4')
plt.title('Clusters of customers')
plt.legend()
plt.show()

